#!/usr/bin/python -O
# -*- coding: utf-8 -*-
## 103architecte.py for 103architecte in /home/rodrig_1/rendu/Maths/103architecte
##
## Made by gwendoline rodriguez
## Login   <rodrig_1@epitech.net>
##
## Started on  Thu Dec  4 11:17:48 2014 gwendoline rodriguez
## Last update Sat Jan 17 15:45:21 2015 gwendoline rodriguez
##

import sys
import math
import numpy

i = 3
n = numpy
mt = math
matrice = n.eye(3)
if (len(sys.argv) == 8):
    x0 = int(sys.argv[1])
    y0 = int(sys.argv[2])
    print "x^4 - ", int(sys.argv[1])
    print "point initial : "+str(sys.argv[i + 1]
    print "méthode de la bissection"
    while (i < len(sys.argv)):
        print "itération "
        i = i + 1
    print "f(x) = "
else:
    import usage
